management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        output:
          destination: posts

security:
  tokenSecret: "ThisIsMySuperSecretTokenWhichNeedsToBeLongEnough"

server:
  port: 8083
