management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

security:
  tokenSecret: "ThisIsMySuperSecretTokenWhichNeedsToBeLongEnough"

server:
  port: 8082
